// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $customers_id_ from "./routes/customers/[id].tsx";
import * as $customers_id_cannot_delete from "./routes/customers/[id]/cannot-delete.tsx";
import * as $customers_id_edit from "./routes/customers/[id]/edit.tsx";
import * as $customers_index from "./routes/customers/index.tsx";
import * as $customers_new from "./routes/customers/new.tsx";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $index from "./routes/index.tsx";
import * as $invoices_id_ from "./routes/invoices/[id].tsx";
import * as $invoices_id_edit from "./routes/invoices/[id]/edit.tsx";
import * as $invoices_id_html from "./routes/invoices/[id]/html.ts";
import * as $invoices_id_pdf from "./routes/invoices/[id]/pdf.ts";
import * as $invoices_index from "./routes/invoices/index.tsx";
import * as $invoices_new from "./routes/invoices/new.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $public_invoices_share_token_html from "./routes/public/invoices/[share_token]/html.ts";
import * as $public_invoices_share_token_index from "./routes/public/invoices/[share_token]/index.tsx";
import * as $public_invoices_share_token_pdf from "./routes/public/invoices/[share_token]/pdf.ts";
import * as $settings from "./routes/settings.tsx";
import * as $templates_index from "./routes/templates/index.tsx";
import * as $Breadcrumbs from "./islands/Breadcrumbs.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/customers/[id].tsx": $customers_id_,
    "./routes/customers/[id]/cannot-delete.tsx": $customers_id_cannot_delete,
    "./routes/customers/[id]/edit.tsx": $customers_id_edit,
    "./routes/customers/index.tsx": $customers_index,
    "./routes/customers/new.tsx": $customers_new,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/index.tsx": $index,
    "./routes/invoices/[id].tsx": $invoices_id_,
    "./routes/invoices/[id]/edit.tsx": $invoices_id_edit,
    "./routes/invoices/[id]/html.ts": $invoices_id_html,
    "./routes/invoices/[id]/pdf.ts": $invoices_id_pdf,
    "./routes/invoices/index.tsx": $invoices_index,
    "./routes/invoices/new.tsx": $invoices_new,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/public/invoices/[share_token]/html.ts":
      $public_invoices_share_token_html,
    "./routes/public/invoices/[share_token]/index.tsx":
      $public_invoices_share_token_index,
    "./routes/public/invoices/[share_token]/pdf.ts":
      $public_invoices_share_token_pdf,
    "./routes/settings.tsx": $settings,
    "./routes/templates/index.tsx": $templates_index,
  },
  islands: {
    "./islands/Breadcrumbs.tsx": $Breadcrumbs,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
